id: I0B68BBEB
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:04:44.370536'
last_modified: '2022-06-18T20:04:44.370549'
parser: null
source_metadata:
  title: Tsong kha pas Essence of True Eloquence (block print), colophon excerpt
  author: tsong kha pa blo bzang grags pa/
  description: 'Digital version 1.0 {Wylie}, diplomatic edition of witness A; WYLIE
    COPY of master xml (completed: 2020-07-23); revision in process, thematic TEI
    markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:blo bzang rgyal mtshan/ (Dharamsala) (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:blo bzang rgyal mtshan/ (Dharamsala) (lg)
  text_witnesses: https://sakyaresearch.org/sources/4867
  bases:
    87fb:
      title: Tsong kha pas Essence of True Eloquence (block print), colophon excerpt
      order: 1
      base_file: 87fb.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
